name       : simsu
version    : 1.3.3
release    : 1
source     :
    - https://github.com/gottcode/simsu/archive/v1.3.3.tar.gz : 435c7b07bddb1e7f93cd13bfd2cfbe6a6ca7e91b2935d5116727db0fcb432798
license    : GPL-3.0
component  : games.puzzle
summary    : A basic Sudoku game
description: |
    Simsu is a basic Sudoku game. You can switch between filling in notes (pencil mode), or filling in answers (pen mode). To make it easier to see where to place numbers, you can highlight all instances of a number. You can also check your answers for correctness while playing. The game stores your current notes and answers, so that you can pick up where you left off the next time you play.
builddeps:
    - pkgconfig(Qt5UiTools)
    - pkgconfig(glu)
setup      : |
    %qmake PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
