name       : simsu
version    : 1.4.2
release    : 7
source     :
    - https://github.com/gottcode/simsu/archive/refs/tags/v1.4.2.tar.gz : 354816fada6829f50ac5ad7e2e63c55b5423accb11a59245fd3407690b574f76
homepage   : https://gottcode.org/simsu/
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : A basic Sudoku game
description: |
    Simsu is a basic Sudoku game. You can switch between filling in notes (pencil mode), or filling in answers (pen mode). To make it easier to see where to place numbers, you can highlight all instances of a number. You can also check your answers for correctness while playing. The game stores your current notes and answers, so that you can pick up where you left off the next time you play.
builddeps  :
    - pkgconfig(Qt6UiTools)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
